### ISSUE TITLE
App not defined

### ISSUE THREAD

**Issue by Kimeiga** [iridakos/rails-chat-tutorial#25] opened 2019-12-01 04:17 UTC
![image](https://user-images.githubusercontent.com/20587215/69909322-6b150b80-13ae-11ea-86f9-77979a6b9c0f.png)
I tried to incorporate this into a Rails 6 application and I'm getting this error. Not sure how to proceed.

**Comment by Yardboy** [comment] 2020-04-23 15:43
I don't know if this is a difference in Rails 6 due to changes in ActionCable, or the fact that Webpacker is now default, but in Rails 6, I got this working with the following...

At the top of `room_channel.js`, add this line:

`import consumer from './consumer'`

Then, change this line:

`App.cable.subscriptions.create(`

... to this:

`consumer.subscriptions.create(`

After that, it should work.

However, I noticed that the chat window did not update automatically until after at least one refresh _after_ clicking a room. Some debugging showed that the `room_channel.js` code was firing only once, when the rooms page was loaded, and was not firing again when a room was clicked (on the `rooms#show` page).

Not sure if this is something to do with Turbolinks or what. Regardless, this meant that the code inside the each loop was getting missed (because the element searched doesn't exist in `rooms#index`) and, as such, the subscription wasn't getting set up.

I solved that by moving the code in `room_channel.js` such that it fires on the `rooms#show` action. The particulars of this are specific to my setup, not going to go into that much detail, but suffice it to say you need to make sure that the subscription code fires whenever a new room is shown.

**Comment by iridakos** [comment] 2020-05-01 00:50
I'm closing the issue but if the case is not resolved by @Yardboy (:+1: for helping) anser, feel free to re-open it.

**Closed by iridakos** 2020-05-01 00:50 UTC

**Comment by chernychort** [comment] 2022-01-15 12:26
@Yardboy Hey, could you explain how to do it? So the broadcast stays in the roommessagecontroller#create right? But the subscription must happen, we a new room is showed, am i understanding this right?

Thanks in advance, just struggling with this last part.

**Comment by Yardboy** [comment] 2022-01-15 17:31
Heya. Yes, the issue is with getting the subscription code firing, not the broadcast.

So, in the tutorial the code in `app/assets/javascripts/channels/room_channel.js` is what handles setting up the subscription to the channel. As implemented, that code was only firing once for me in Rails 6 with TurboLinks, when the page was loaded. It did not fire when I clicked on a different room in the UI, which means I wasn't getting a subscription set up for the room I had clicked, resulting in no updates until I refreshed the page (which re-fires the `room_channel.js` code).

This is because changing pages via TurboLinks doesn't cause that `room_channel.js` code to fire, only a full browser refresh does. The solution is to tie that code into TurboLinks refreshes via the `turbolinks:load` event.

The way my .js is setup, I have classes defined for each controller-action combination, and on a `turbolinks:load` the `#setup()` function in the appropriate class is fired. In this case, that's `RoomsShowPage`, so I put the `room_channel.js` code inside the `RoomsShowPage#setup()` function, and then clicking on a new room immediately set up the subscription and started showing updates.

So, somewhere in your application, wherever appropriate, you need this:

`$(document).on('turbolinks:load', <call the room_channel.js code>)`.

**Comment by Yardboy** [comment] 2022-02-06 18:30
@chernychort Just checking in to see if the explanation above helped you.
